# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5aaf3867340ae2f440953b1e8600825aa07962acffc30fa686ec05b486c7ed2f168f6fed08c749228f1f82a9b09a4157ecc96628ae39f48c6b078c1598b991d

test:
  secret_key_base: f6dec23096c447adc73732366d90abaf7127b145f6af4826c785251ef5f682f1647a6016127e4c2294c76dc4297c2bed69ba2843ce72a6e51e086c544c70978f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
